version: '3'
services:
  mysql:
    image: mysql:8.0.12
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: sample
    ports:
      - 3306:3306
    volumes:
      - ./tmp/mysql:/var/lib/mysql
      - ./test/initdb.d:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
